---
# Default variables for the deploy role
app_name: "clearway"
deploy_user: "deploy"
deploy_user_home: "/home/{{ deploy_user }}"
app_base_dir: "{{ deploy_user_home }}/deployments"
frontend_port: 3000
backend_port: 8000