---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: Restart Docker service
  ansible.builtin.systemd:
    name: clearway-docker
    state: restarted
    enabled: yes
  become: yes